### PR TITLE
Alternate Fix For Approval

### PR DESCRIPTION
**Pull request by SillyInventor**
Added a hook to the Ownership table that updates the Project table.

Some day we all need to have a talk about why we made libraries that don't merge back to the original teams, but which we don't want to be part of the project.

### CODE REVIEW

**Comment by chuck211991** [comment]
You should check and make sure the object that is getting saved is Project object prior to saving it.

And the reason we didn't just add it into the original codebase was because there was a very lofty goal of creating a system that would allow one to filter out all objects that a user doesn't have access too without explicitly specifying models that need to be monitored. If you look at the django_teams code, there is a function to replace all default managers with a manager that first checks for their permission. This worked great, except for related models. And that proved to be a bigger bump in the road than anticipated.

We had this lofty goal because we didn't want to redo the forum, tags, or even the projects really. Because that's work, and I hate work.

**Comment by JamesHoustonDavis** [comment]
I'm sorry, it's still not clear to me. We made changes, those changes never get returned to django_teams... why don't we just accept it as our own and make it site specific? Is it getting returned? Are we using it for other things?

**Comment by JamesHoustonDavis** [comment]
I just realized why the content type check was needed.... though there is no object in ownership that isn't a project, there could be technically.

**Comment by chuck211991** [comment]
There is potential that I would reuse that app; it is a very common problem, and Django is big on DRY (Don't Repeat Yourself). 

And there may be cases where that comes up on the future; for example, if the forum ever comes back, we will want forums to belong to a classroom, and this app would help with that.

**Comment by BenjaminDHorne** [comment]
Should I still be testing and merging this code?

**Comment by SillyInventor** [comment]
Yes, please do Ben.

@ Charles, If you were planning on reusing it...  there are hard coded references to 'classroom', 'teacher', and 'student'. There is also, under fragments, already a project_share component which seems very site specific.

Point taken about the need for content type checking. Though all those objects would appear in the same list as projects in the same order they were added and to display them publicly you would need to add a fragment for them... just saying.... kind of specific to the site.

**Comment by chuck211991** [comment]
Yeah, there was a rush to get this feature out before David and I left and I wasn't watching carefully enough. Would you mind moving the folder here (https://github.com/chuck211991/django_teams/tree/master/django_teams/templates/ **django_teams/fragments/project_share**) to (https://github.com/GK-12/rpi_csdt_community/tree/master/project_share/templates)? Then I'll remove them from Django Teams.

As for the classroom references, I need to add a feature to Django Teams that allows one to override the names in settings.py. Just haven't made it that far. 

None of this is code though; it won't break if a different app uses Django Teams. Adding in the code that referenced project_share would have made project_share required.

**Comment by SillyInventor** [comment]
Tried, but that breaks it. I'm not an expert but I think it might be that this section is kind of specific?:
<code>
def load_fragment_template(object):

    ct = ContentType.objects.get_for_model(object)
    template_name = 'django_teams/fragments/%s/%s.html' % (ct.app_label, ct.model)
    try:
        template.loader.get_template(template_name)
        return template_name
    except template.TemplateDoesNotExist:
        return "django_teams/fragments/default.html"
</code>

I guess what I am saying is that if you wanted to use it in a different project, you would need to add a new component or two and change names. And if you want it to be able to own different objects then you should add multiple forms & display for each, which may easily become site specific. These changes would require editing the library, which makes it a great template, but a weird library IMO.

**Comment by chuck211991** [comment]
Django looks for templates in the directories specified in settings.TEMPLATE_DIRS and <app>/templates. To add a template fragment for django teams, you should do something like:
```
cd rpi_csdt_community
mkdir -p project_share/templates/django_teams/fragments/project_share
echo "This is the project template" > project_share/templates/django_teams/fragments/project_share/project.html
```
It looks like a lot of stuff was added to django_teams that shouldn't be there, but it snuck past my review because it didn't raise any errors (it never imports from project share). I'll fix some of it tonight and get back to you (this is why I left the repo in my account; it's my project, not GK12's).

To add support from an app for django_teams, one needs to:
* Create the template fragments
* Add controls in their views to limit who can see what
 - The teamify decorator might still work, in django_teams.decorators.teamify, in which case you would do something like this in urls.py:
```
...
    url('/projects/', teamify(project_share.ProjectListView), name="project-list"),
...
```

And that is it. Then you have:
 * Teams
  - Including creating, joining, modifying, etc.
 * Access controls and moderation
  - Limited to public/private teams, and approved (viewable) or unapproved (not viewable) objects

**Comment by SillyInventor** [comment]
Sincere apologies. I excluded the django_teams directory the first time round.

Please let me know when you make the changes.

**Comment by chuck211991** [comment]
Alright guys, I made some changes to Django teams. It should work a bit better now... Please see this commit: https://github.com/chuck211991/django_teams/commit/27639587a3fe306792dabf867cac8702dc348b40

**Pull request merged**
