### PR TITLE
Updated application_csnap for 3D

### PR DESCRIPTION
**Pull request by SillyInventor**
Merge this before you upload 3D CSnap.

### CODE REVIEW

**Comment by ibara** [comment]
Noted. Thank you!

**Comment by chuck211991** [comment]
As a spectator, this is a reminder that you should not be adding JS files to codebase directly like this. You can make a module to add three.js, just like we did for SoundJS (https://community.csdt.rpi.edu/admin/project_share/application/31/). 

But it's up to you guys, good luck :-P.

**Comment by ibara** [comment]
This is a contentious spot, and I'm not going to say my opinion carries any more weight than just one fellow (since it doesn't) but I have from the beginning hated the module loader and the idea of writing modules.

I get the point of being able to sync with UCB. I still think we are better off going it without them. I don't think we win by playing understudy to them. We represent not just an alternative to Snap, not just an alternative to STEM education--which have significant gravity on their own--but a profound "what if" to what it means to be Open Source. We're shining light onto a blind spot in Open Source that could make Open Source better as a phenomenon. We don't get there if, by asking "what if," we do it entirely under the auspices of UCB.

Of course, I'm not the only one who has to live with such a decision, so I defer to the collective will and the will of @eglash.

**Comment by ibara** [comment]
Now, that doesn't mean we ignore UCB entirely. And it doesn't mean we don't incorporate fixes from them and send fixes back. But we ought to do it as an entity with greater agency and independence.

**Comment by SillyInventor** [comment]
... see, and I was just going to leave this thread alone...

Honestly, I couldn't care less whether or not we can pull from UCB automatically. I know that it's unlikely that the code will ever merge or pull from Berkeley because our code changes have never been properly confined and no one intends to fix it. Additionally it's part of Eglash's grant proposal with Charles now, meaning we dare not do it before we get money, and any pulling will require active fellows doing development to keep stability. I also know that it could be useful to pull any work that they do and that it could make cross development easier in the future.

To me, it's all about readability, ease of use, and laziness. I don't know who thought it was a good idea to put all of SoundJS in a single line so that I have no hope of ever reading or using it.... I also don't know who thought uploading and displaying it on the site without a context, a project, or any review so that I get a late night email from Eglash asking me to remove it from the create page... However, 3D comprises 40,000 lines of code and several changes to all the larger gui and object components which would need to be included. It seems monstrous to put all that in a single file regardless of how careful I am to break it up.

Snap! is many things, but it is not efficient, it takes nearly a minute to load just the tutorial module which is 1000 lines: I don't want to see what it's like loading tens of thousands of lines of code. It's my worst nightmare, take 10 minutes to load test module, take 1 minute to debug and reload again.

Finally, there are several parts of the code that would simply have to be rewritten. It's not that I couldn't rewrite it so that it's all self referential, and gets loaded in via the module loader, but it seems like a lot of work. Unless I actually have a good reason to rewrite everything to be harder to use and develop with, I'm simply not going to.

**Comment by eglash** [comment]
I like the concept of laziness as a design principle.

And I like the idea that there is merit to having CSnap stand on its own 6 legs. That is a challenge to convey that to many CS folks -- If you said we were creating a special purpose version made to deal with some technical challenge—high resolution graphics, or interfacing with gesture movements, or whatever – that would make sense to them. But telling them we are making a “cultural” version is incomprehensible. What could “culture” possibly demand that isn’t utterly trivial? It’s not until you actually try carrying out these cultural simulations that you start to see there are real computational challenges (soundJS being one of them!).

RE

**Comment by SillyInventor** [comment]
Thank you. I came up with it myself.

**Comment by eglash** [comment]
I actually have a whole file on laziness – for example this quotation from the US patent office:

“It is a well-known fact that the horse hay rake was first invented by a lazy negro [sic] who had a big hay field to rake and didn't want to do it by hand.”

I’ve been planning to write an essay on it, with the title “Laziness is the Mother of Invention.” But every time I try, I start to think “this would be a great time for a nap”….

RE

**Comment by ibara** [comment]
Speaking of labor (even if it is in the form of laziness):
James should not be getting those kinds of late-night emails. I should. That's my job.
James, Ben, and Brenda are all deep in writing JavaScript code (whether or not James necessarily wants to). Other than reviewing and making small tweaks (like adding a newline at EOF or fixing typos), I'm not. My job is to keep everything running smoothly so that everyone can do what they do best--whether it's writing CSnap JS code or scripts.
Anything that sounds like a support task is my responsibility.

**Comment by eglash** [comment]
Brenda that reminds me, I promised to send you more info on sound and js – I spotted a couple of projects:

1)      Concatenating audio files: http://blog.ragingflame.co.za/2013/5/31/using-nodejs-to-join-audio-files

2)      Playing multiple sounds simultaneously: http://www.html5rocks.com/en/tutorials/webaudio/intro/#toc-abstract
Putting those two together, it should be possible to

a.       Concatenate all the sounds specified by the user in a special audio loop block.

b.      Play the concatenated files simultaneously with those of other audio loop block.

RE

**Comment by chuck211991** [comment]
On 08/03/2015 19:19, Silly Inventor wrote:
>
> To me, it's all about readability, ease of use, and laziness. I don't 
> know who thought it was a good idea to put all of SoundJS in a single 
> line so that I have no hope of ever reading or using it....
>
Take a look here: 
https://en.wikipedia.org/wiki/Minification_%28programming%29
And the SoundJS distribution
>
> I also don't know who thought uploading and displaying it on the site 
> without a context, a project, or any review so that I get a late night 
> email from Eglash asking me to remove it from the create page...
>
I don't think it should have been there; it was meant to be a dependency 
of other modules, such as the Rhythm Wheels project, and should not have 
been showing up on it's own.
>
> However, 3D comprises 40,000 lines of code and several changes to all 
> the larger gui and object components which would need to be included. 
> It seems monstrous to put all that in a single file regardless of how 
> careful I am to break it up.
>
Is including 40k lines in every application really a good idea though? 
See the below comment.
>
> Snap! is many things, but it is not efficient, it takes nearly a 
> minute to load just the tutorial module which is 1000 lines: I don't 
> want to see what it's like loading tens of thousands of lines of code. 
> It's my worst nightmare, take 10 minutes to load test module, take 1 
> minute to debug and reload again.
>
This is exactly the purpose of the module loader; adding in 1 MB of JS 
that only gets used by 3d modules will slow down other modules a lot. 
Especially consider the cases of places that don't have great internet 
connections, like Africa

**Comment by chuck211991** [comment]
This was not the primary reason for the module loader. We prototyped 
using CSnap as a replacement for pCSDT's while sitting in an airport on 
the way to California; using a module loader allowed me to prototype 
quickly with minimum changes to the codebase.

But, even bigger than that, the old pCSDT's had a lot of copy and pasted 
code, which is bad bad bad. When a new app was wanted, they would copy a 
previous version, make a few changes, and call it done. Fixes would be 
made to one app, but not propagated to other apps. This was the main 
reason for the module loader.

Syncing with UCB was not really a real objective until much later (it 
was on the list of benefits to the module loader though, since it was a 
potential benefit), when Brian joined.

**Comment by SillyInventor** [comment]
Having tried loading with both the loader and a HTML refernce, I feel I can say that referencing code via HTML is far faster than loading in via the module loader for large code sets. I see almost no delay with the former, and no change in the performance of the other modules.

 I do understand minification, but not why it was used on a developing module. Was Kathryn meant to read or use that for her work? Although I am glad to hear that it was just an oversight that it got put on the create page.

As one of the main users of the module loader, I quite like it for creating new apps. But if the objective is not to sync with UCB, I see even less reason to care if we mod the code base for something this massive. Any change to the code base will flow through, and 3D could hardly be characterized as a quick prototype and will spawn (probably) several smaller modules for arcs, bucky balls, pyramids and more.

**Comment by ibara** [comment]
> But, even bigger than that, the old pCSDT's had a lot of copy and pasted code, which is bad bad bad. When a new app was wanted, they would copy a previous version, make a few changes, and call it done. Fixes would be made to one app, but not propagated to other apps.
Other than the last line, where it means no one ever bothered to run `diff` and `patch` (especially when svn does it for you) I don't see how this is bad.

**Comment by eglash** [comment]
Thank you, Ron. This "sounds" fascinating. Honestly, this is really intriguing and keeping these resources will be crucial for my understanding.  You just supplied a theme for a few blogs! 
To reveal my thoughts a little more, I am stunned by what I have learned in a few short months with this Fellowship. Yet, anxiety about what remains to learn and do is overwhelming at times. 
See you tomorrow,
Brenda ThomsonGraduate StudentMS in ITWSRensselaer Polytechnic Institute 

-------- Original message --------
From: "Eglash, Ron" <eglash@rpi.edu> 
Date: 08/03/2015  19:22  (GMT-07:00) 
To: Brenda Thomson <thomsb2@rpi.edu> 
Cc: CSnap/rpi_csdt_community <reply@reply.github.com>, CSnap/rpi_csdt_community <rpi_csdt_community@noreply.github.com> 
Subject: RE: [rpi_csdt_community] Updated application_csnap for 3D (#57) 



Brenda that reminds me, I promised to send you more info on sound and js – I spotted a couple of projects:
1)     
Concatenating audio files:

http://blog.ragingflame.co.za/2013/5/31/using-nodejs-to-join-audio-files
2)     
Playing multiple sounds simultaneously:
http://www.html5rocks.com/en/tutorials/webaudio/intro/#toc-abstract
Putting those two together, it should be possible to
a.      
Concatenate all the sounds specified by the user in a special audio loop block.
b.     
Play the concatenated files simultaneously with those of other audio loop block.
 
RE

**Comment by ibara** [comment]
@eglash -- Did you intend to post Brenda's personal reply to you?

**Comment by eglash** [comment]
I am confused by your question – I did not post anything, I simply received a message from her.

**Comment by ibara** [comment]
For some reason, GitHub posted her reply under your name. (please see: https://github.com/CSnap/rpi_csdt_community/pull/57#issuecomment-127623458 )

**Comment by ibara** [comment]
Merged in prep for an update tonight.

**Pull request merged**
