### PR TITLE
Added a api/team request

### PR DESCRIPTION
**Pull request by SillyInventor**
This is meant to allow C-Snap to query which classrooms a user is a
member of. To do this you send api/team/?owner={number} and then it
returns name and team number.

### CODE REVIEW

**Comment by BenjaminDHorne** [comment]
Awesome. Ill check it out ASAP.

**Comment by ibara** [comment]
Very cool.
Unfortunately, can't test atm. But lmk how everything checks out.

**Comment by chuck211991** [comment]
Bonus points if you write some tests for this; see project_share/tests/test_api.pyIf the user accesses this page without logging in, it will crash (comment left inline).

If the user accesses this page without logging in, it will crash (comment left inline).

Are you sure create works? I think you need status in the fields, or to set that automatically in the override like you did with owner (although, I don't see an owner field in the edge version of django_teams==1.0.1; what version are you testing with?)
If the user accesses this page without logging in, it will crash (comment left inline).

Have you considered just adding a teams field to the user API? That would be more inline with seperation of concerns (and someday I'll make an API for django_teams)

**Comment by SillyInventor** [comment]
I have added a test, though I must confess I don't know how to actually use it other than to check the build fail.

I have (by injecting code into the Javascript) created projects tied to a specific classroom by appending the category to the post. All it does is designate the classroom in the object so that when you eventually press publish it creates the ownership item etc.

I have changed the url request to use ?user={number} instead of owner. I had previously left it as owner to be consistent with other C-Snap requests. But decided to change it to user per your suggestion Charles, it seems more logical to be consistent with the database.

You do not need to specify the role from C-Snap. However, I have added a filter for members and owners only.

I have considered amending the api/user... but I think it much better to be consistent with the way C-Snap gets everything else.

**Comment by BenjaminDHorne** [comment]
I will look at this stuff tomorrow after the dev meeting.

**Comment by chuck211991** [comment]
You can use it by running...

```
. ./activate
python manage.py test
```

Look at the Django testing documentation for more information.
https://docs.djangoproject.com/en/1.8/intro/tutorial05/

**Comment by SillyInventor** [comment]
Thank you Charles, that's very helpful.

**Comment by ibara** [comment]
Just a reminder that a new release will be cut on Friday, if this is something we want to test.

**Comment by BenjaminDHorne** [comment]
I will be testing any code that needs to be today.

**Pull request merged**
