### PR TITLE
Django update

### PR DESCRIPTION
**Pull request by chuck211991**
This update is going to require some time to get onto the live server; I tested with a local copy of the live data, and the migrations worked (mostly), but we'll need to have a little party...

### CODE REVIEW

**Comment by SillyInventor** [comment]
Hmm, a party might be a good idea, and I think, selfishly, that we can check my CSnap pull request at the same time and move to the DEV for testing. Perhaps after spring break? Ibara, Ben, what do you two think?

**Comment by BenjaminDHorne** [comment]
Yeah we should do that.

**Comment by ibara** [comment]
+1 for party

**Comment by BenjaminDHorne** [comment]
Tuesday 3 to 5 work?

**Comment by ibara** [comment]
Yup!

**Pull request merged**
