### PR TITLE
Static context pages

### PR DESCRIPTION
**Pull request by chuck211991**
Basic implementation to support creating context pages in HTML, linking them together with a menu, and rendering them.

This is the first step to addressing https://github.com/CSnap/rpi_csdt_community/issues/116

### CODE REVIEW

**Comment by chuck211991** [comment]
Note that this relies on pull request #115 ; after that is merged, this will look much smaller.

**Comment by SillyInventor** [comment]
@bbabbitt2003 as time progresses you seem to be moving farther away from this. Please review and accept or close.

**Comment by chuck211991** [comment]
The method we are looking to use should be reviewed, including the proposed change to the system architecture. Bill, can you start either an empty PR or create an issue for discussion?

**Comment by SillyInventor** [comment]
Don't start an empty PR. That's not the place for discussion.

**Comment by chuck211991** [comment]
The real place for discussing the proposed changes would be a PR; but since Bill and Ron want to try and keep the cultural content under wraps (as to not infringe on the rights of the cultures that contributed), we can't do a true PR. An empty PR, maybe with a link (or reference) the appropriate repo behind RPI's firewall, would server just as well, and effectively mark where we made the transition. If we just do an issue, it would be hard to say "we started using the new system here", and even harder to search through the Git log for.

**Comment by SillyInventor** [comment]
I completely disagree. All discussion about what should be done, structure, and design should take place on the relevant issue. PRs are for reviews of details about execution.

**Comment by chuck211991** [comment]
*shrug*. I see some logic in that, hence my earlier statement with the disjunction, but we should document the discussion somewhere.

**Comment by chuck211991** [comment]
@bbabbitt2003 ...

**Comment by bbabbitt2003** [comment]
moving to a static site

**Pull request closed without merging**
