### PR TITLE
Whoops

### PR DESCRIPTION
**Pull request by SillyInventor**
This is an important fix for the site... the content type needs to be properly imported...

### CODE REVIEW

**Comment by ibara** [comment]
This merge feels weird... 3 commits to make a 1-line change?
Merged, but please double check.

**Comment by ibara** [comment]
Do a git commit --amend and git push --force if it's not right.

**Comment by ibara** [comment]
Dev site updated with this fix.

**Comment by SillyInventor** [comment]
Is this really up? I'm still getting the same error on publish project.

**Comment by chuck211991** [comment]
A little bit late, but I've discovered the best way to undo commits is a soft reset. I.e.
```
git reset --soft HEAD~3
git commit -a
```

**Comment by ibara** [comment]
I'm filing this under "more reasons I hate git" :-)

**Pull request merged**
