### PR TITLE
Removed deprecated template processor from allauth

### PR DESCRIPTION
**Pull request by chuck211991**

### CODE REVIEW

**Comment by chuck211991** [comment]
Note that the live site will have to have a number of packages updated to make it compatible with this change...

**Comment by ibara** [comment]
Are you going to do it? I'm in Denver for the AAA conference until Thanksgiving essentially so I won't be able to do this.

**Comment by bthomson2** [comment]
Is it okay for me to do this merge? This comment "Note that the live site will have to have a number of packages updated to make it compatible with this change." makes me unsure, as I don't want to cripple the site.

**Comment by SillyInventor** [comment]
Only merge code you have personally tested and vetted yourself. I will come back and do admin work once my schedule clears up.

**Comment by BenjaminDHorne** [comment]
Yeah, sorry i havent had a chance to test this yet. My schedule has been
packed this semester, especially right now.

**Comment by ibara** [comment]
DO NOT MERGE THIS UNTIL WE UPDATE DJANGO AND THE LIBRARIES.

**Comment by SillyInventor** [comment]
This is not compatible with changes made to Settings for the Django update.

**Pull request closed without merging**
