### PR TITLE
Setup Vagrantfile, other install scripts.

### PR DESCRIPTION
**Pull request by chuck211991**
This should greatly simplify development startup. Please see the Wiki
for more information about getting started
(https://github.com/CSnap/rpi_csdt_community/wiki/Setting-up-for-Development)

### CODE REVIEW

**Comment by chuck211991** [comment]
How about we change the README.md file to link to the install wiki page (we should only have one copy of those instructions, otherwise we have to maintain both). We could even have the README link to (or become) https://github.com/CSnap/rpi_csdt_community/wiki/Development-Workflow, which needs a bit more work. 

I'm OK with removing Putty instructions.

Did you make sure to runserver as "python manage.py runserver 0.0.0.0:8000"?

**Comment by SillyInventor** [comment]
I'm ok with having the readme point to the wiki. We should also preserve the current setup in a page 'old setup procedure' or similar.

Running with specified IP fixed it. Thanks.

I will put in an extra bit of time and build it on windows. If you can change the readme, I will edit the wiki.

**Comment by chuck211991** [comment]
The old setup instructions are in version control; so the question is do you want to support those (in which case we should call it "manual configuration"), or archive them (in which case we should leave them in Git)?

**Comment by chuck211991** [comment]
We should move the workflow section of the wiki to it's own page; it complicates the setup (there are also a few bits missing; we should call git fetch before creating a new branch, and information on updating the personal repo from upstream).

**Comment by SillyInventor** [comment]
When you called before, I thought I'd accidentally added a command for virtualenv, the '. ./activate' call is to install libraries, not to activate the virtualenv and was in the original guide. We can replace this with a pip call once we resolve #125.

What do you think of the [changes to the wik](https://github.com/CSnap/rpi_csdt_community/wiki/Setting-up-for-Development)i? 

vagrantup.com is down for me atm. I will test on windows later tonight (hopefully).

**Comment by SillyInventor** [comment]
The only change I had to make to get this to build was to append beautifulsoup~=3.2.1 to libraries.txt.lock.  Besides that, I was able to follow the instructions verbatim and get a good build.

**Comment by ryaholm** [comment]
Wiki instructions worked for MacOS.

**Comment by SillyInventor** [comment]
Just append beautiful soup to the lock file, and I can approve and merge.

**Comment by chuck211991** [comment]
It looks like BeautifilSoup4 is already in the lock file;

```
  1 bbcode~=1.0.24
  2 BeautifulSoup4~=4.5.3
  3 coverage~=4.2
  4 Django~=1.9.5
...
```

I adjusted the ordering of the links in README.md. Also, the changes to the Wiki look great. I added a page for "Manual installation".

**Comment by SillyInventor** [comment]
I know beautifulSoup 4 is in there, but one of the tests requires beautifulSoup 3.2.1, per my previous comment. Try setting up vagrant and running 
`python manage.py test`
you should get unittest.moduleLoader fails.

To be fair, you can also change the test so it doesn't fail, but I'd rather do that in a separate pull request (when we consolidate the libraries).

**Comment by chuck211991** [comment]
Interesting. It had worked earlier. I think this problem was introduced in https://github.com/CSnap/rpi_csdt_community/commit/33dd3dd9b5538d7495bc9528b5cda25f495bd04e to fix running on Windows; so now the question is, why was it changed then?

**Comment by hughed2** [comment]
I changed it because BeautifulSoup 3.x is Python 2 only.

**Comment by SillyInventor** [comment]
Do not revert BeautifulSoup4, it will break other people's builds. Instead append beautiful soup so I can merge, and then make a new branch so we can consolidate libraries per issue #125.

**Comment by chuck211991** [comment]
Gotcha. Ok, we'll have to look into that at a later time then (and fix the test). Does this look good, James?

Thanks, @hughed2 for chiming in :).

**Comment by SillyInventor** [comment]
simultaneous comments are simultaneous.

**Comment by chuck211991** [comment]
Append it to what? libraries.txt.lock? That will have the same effect as what I did

**Comment by SillyInventor** [comment]
Do not delete BeautifulSoup4, have BeautifulSoup4 AND BeautifulSoup. I've already tested it, and it works fine.

**Comment by chuck211991** [comment]
Good call on psycopg2, negligence on my part.

If either works when installed, without changing import statements, it means that they have the same name/folder within the site-packages folder. This means that when we install them, whichever gets installed second will override the first (or, if they do get installed side-by-side, which ever gets listed first will be included by Python... maybe.). Did you confirm that it still works with Python 3 when both are installed?

Also, getting to work with Python 3 is not a current objective, and will likely require more than just including a second version of that library. David did not do a thorough test, and even said "no guarantee everything works perfectly on python3, but this should at least fix the first few errors you run into" in his commit. I propose that we leave that out until we are ready to switch over to Python 3.

**Comment by ibara** [comment]
As per Charles's request, I'll try this out over the weekend.

**Comment by SillyInventor** [comment]
Have tested and works. Sorry @hughed2, try building with vagrant for the time being.

**Pull request merged**
