### PR TITLE
add requested menu bar change

### PR DESCRIPTION
**Pull request by BenjaminDHorne**
This is the change Ron wanted to the menu bar. Basically just made selected items larger. Once this is up on the site, I will go through and delete the titles he wanted deleted with this change.

### CODE REVIEW

**Comment by SillyInventor** [comment]
This caused a build failure on drone. I can't take a look ATM, but you may wish to review it here:
https://drone.io/github.com/CSnap/rpi_csdt_community/18

**Comment by BenjaminDHorne** [comment]
Its literally just a small css change... I will take a look though.

**Comment by ibara** [comment]
Should I go ahead and update the live site?

**Comment by SillyInventor** [comment]
Please do dev site first, and check...


Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by BenjaminDHorne** [comment]
All this should do is change how the menu bars look slightly. If you put it
on Dev, ill check it out. Then we can push it live so I can make those
other changes.

**Comment by ibara** [comment]
OK, I'll push it to the dev site

**Comment by hughed2** [comment]
The issue isn't with Ben's code, it's because you're not setting any kind of version requirements for all the libraries you pull. Django-reversion 2.* doesn't work with django-cms. You can probably fix by updating libraries.txt:26 to 

django-reversion=1.10.2

until the reversion team fixes their bug.

**Comment by SillyInventor** [comment]
Thanks David. I love it when you save me time.

I still think testing on the dev site is a good idea, but you can probably do both in relatively rapid succession.

**Comment by ibara** [comment]
Updating the dev site now, will let you know when it's done.

**Comment by BenjaminDHorne** [comment]
Thanks man.

**Comment by ibara** [comment]
Done.

**Pull request merged**
