### PR TITLE
Switch to Travis

### PR DESCRIPTION
**Pull request by SillyInventor**
Remove offending submodules blockly temoporarily, add travis.yml, change settings to include new database, update activate to run correctly, update readme, fix test cases in fixtures

### CODE REVIEW

**Comment by chuck211991** [comment]
Why are we switching to Travis?On Feb 20, 2017 22:08, Silly Inventor <notifications@github.com> wrote:Remove offending submodules blockly temoporarily, add travis.yml, change settings to include new database, update activate to run correctly, update readme, fix test cases in fixtures



You can view, comment on, or merge this pull request online at:
  https://github.com/CSnap/rpi_csdt_community/pull/118

Commit Summary
Remove offending submodules blockly temoporarily, add travis.yml, change settings to include new database, update activate to run correctly, update readme, fix test cases in fixtures

File Changes

    M
    .gitmodules
    (6)
  
    A
    .travis.yml
    (30)
  
    M
    README.md
    (24)
  
    M
    activate
    (6)
  
    M
    project_share/fixtures/default.json
    (46)
  
    M
    rpi_csdt_community/fixtures/test_data.json
    (46)
  
    M
    rpi_csdt_community/settings.py
    (32)
  
    D
    static/closure-library
    (1)
  
    A
    static/js/create/style.less
    (25)
  
    D
    static/scratch-blocks
    (1)
  

Patch Links:
https://github.com/CSnap/rpi_csdt_community/pull/118.patchhttps://github.com/CSnap/rpi_csdt_community/pull/118.diff

**Comment by SillyInventor** [comment]
Drone moved, our hopefully new partners (LLK) use travis, and so I can put in coveralls soon.

**Comment by chuck211991** [comment]
We (had) coveralls setup for a bit; it's just a matter of attaching the test coverage analysis to the CI. I think it was setup on Drone, but wouldn't bet on it.On Feb 20, 2017 22:41, Silly Inventor <notifications@github.com> wrote:Drone moved, our hopefully new partners (LLK) use travis, and so I can put in coveralls soon.

**Comment by SillyInventor** [comment]
Yes, but I'd like to put it back. I'm also hoping to put in greenkeeper.

**Pull request merged**
