### PR TITLE
Fix to 500 Error

### PR DESCRIPTION
**Pull request by BenjaminDHorne**
This is the fix to the 500 error received when saving project to a null classroom

### CODE REVIEW

**Comment by chuck211991** [comment]
This was closed and merged somewhat prematurely...

Why are there 2 commits? Shouldn't this be just 1 commit?

Did this fix the problem? I'm slightly concerned that is creating an
project_share.models.Approval object with nothing but default values;
I'm surprised it doesn't cause an error 500 due to 'project' being
undefined.

Also, Ben, you don't need to leave that comment in there. It should be
in the Git logs who, when, and why you changed it...

Thanks,
  Charles

**Comment by BenjaminDHorne** [comment]
Yeah my git for messed up on my local machine, so I did a weird work around
just to get it up. It should be 1 commit.

**Comment by SillyInventor** [comment]
The problem here is that the form does not get saved when pressing the publish button. There are many solutions, and there is nothing particularly wrong with the one you purpose. However, I recommend simply forcing the publish button to save first. You can do this as below:

First give the generic form in generic_form.html a handle with an id:

    {% if form.is_multipart %}
        <form id="generic_form" class="form-horizontal" method="post" action="{{ action }}" enctype="multipart/form-data">
    {% else %}
        <form id="generic_form" class="form-horizontal" method="post" action="{{ action }}">

Then make the publish button post the generic form in project_edit.html, but with the request from publish project not submit:

    <input type="submit" form="generic_form" name="publish_project" class="btn btn-large btn-primary" value="Publish Project"></input>

Then in the views>ProjectUpdate, check to see in the post if you are getting the request from publish project or not. To do this you need to override the post and redirect when it comes from publish project:

    def post(self, request, *args, **kwargs):
        if 'publish_project' in request.POST:
            super(ProjectUpdate, self).post(request, *args, **kwargs)
            o = super(ProjectUpdate, self).get_object()
            return redirect('approval-create', project_pk=o.pk)
        return super(ProjectUpdate, self).post(request, *args, **kwargs)

That should be all that is required.

**Comment by BenjaminDHorne** [comment]
Oh yeah shoot, you are right. I didn't check if it was saved. Ill fix this
asap.

**Pull request merged**
