### PR TITLE
Updated applicatoin_csnap for 3D

### PR DESCRIPTION
**Pull request by SillyInventor**
Added some static resources. Don't pull this until we're ready for 3D.

### CODE REVIEW

**Comment by ibara** [comment]
The merge I just made will be OK without this though, right?

**Comment by SillyInventor** [comment]
So the release you cut will be fine. But when the 3D stuff goes up, we need this change to load CSnap.

**Comment by ibara** [comment]
The release I cut (and am about to upload) doesn't have the 3D stuff in it. I know people are only going to want to play with 3D but we need them to test the community site fixes.

I'll upload 3D CSnap to the dev site Tuesday night, after uploading the community site fixes to the live site.

**Comment by SillyInventor** [comment]
Sounds good to me.

**Comment by SillyInventor** [comment]
I need to make a pull request for a fix to the dev site, so I will reopen this later.

**Pull request closed without merging**
